2020-01-14 11:01:54.100892
Traceback (most recent call last):
  File "E:\tirpude_cms_new\notice\views.py", line 170, in filter_notice
    show_notice = eval(filter_str)
  File "<string>", line 1, in <module>
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\lookups.py", line 72, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1211, in get_prep_value
    return self.to_python(value)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1186, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ['“01-01-2020” value has an invalid date format. It must be in YYYY-MM-DD format.']


