

2020-01-07 12:03:27.695893
Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\authentication\views.py", line 134, in admin_signup
    obj_sections = Sections.objects.all()
NameError: name 'Sections' is not defined


2020-01-07 12:03:29.951968
Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\authentication\views.py", line 134, in admin_signup
    obj_sections = Sections.objects.all()
NameError: name 'Sections' is not defined


2020-01-08 16:40:15.664005
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:46:10.967181
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:46:15.333440
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:50:44.489176
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:53:39.462467
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:53:42.508723
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:56:17.256095
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:56:19.877243
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:56:41.025466
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'All'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 517, in show_particular_student_book
    book_obj = BooksIssue.objects.filter(fk_user_info_id=student_name)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got 'All'.


2020-01-08 17:00:51.672163
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:00:52.988726
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:01:27.380887
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:01:28.756359
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:15:03.932823
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 80, in filter_author_title
    return HttpResponse(json.dumps(title_list))
UnboundLocalError: local variable 'title_list' referenced before assignment


2020-01-08 17:15:35.484929
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 60, in filter_title
    return HttpResponse(json.dumps(title_list))
UnboundLocalError: local variable 'title_list' referenced before assignment


2020-01-08 17:17:51.111762
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:17:52.396980
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:17:54.708685
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:18:53.446463
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 80, in filter_author_title
    return HttpResponse(json.dumps(title_list))
UnboundLocalError: local variable 'title_list' referenced before assignment


2020-01-08 17:19:16.636869
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:19:18.405437
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 18:01:17.979655
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 18:01:19.469788
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 18:16:40.507235
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 18:16:41.798494
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-09 10:29:43.019454
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 130, in delete_book_purchase
    book_obj.delete()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\base.py", line 936, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 245, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 28, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'BooksPurchase' because they are referenced through a protected foreign key: 'BooksIssueData.fk_book_purchase'", <QuerySet [<BooksIssueData: c>]>)


2020-01-09 10:29:49.724212
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 130, in delete_book_purchase
    book_obj.delete()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\base.py", line 936, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 245, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 28, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'BooksPurchase' because they are referenced through a protected foreign key: 'BooksIssueData.fk_book_purchase'", <QuerySet [<BooksIssueData: c>]>)


2020-01-09 10:33:53.466898
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 130, in delete_book_purchase
    book_obj.delete()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\base.py", line 936, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 245, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 28, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'BooksPurchase' because they are referenced through a protected foreign key: 'BooksIssueData.fk_book_purchase'", <QuerySet [<BooksIssueData: c>]>)


2020-01-09 10:34:00.283795
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 130, in delete_book_purchase
    book_obj.delete()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\base.py", line 936, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 245, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 28, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'BooksPurchase' because they are referenced through a protected foreign key: 'BooksIssueData.fk_book_purchase'", <QuerySet [<BooksIssueData: c>]>)


2020-01-09 10:34:55.879336
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 130, in delete_book_purchase
    book_obj.delete()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\base.py", line 936, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 245, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 28, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'BooksPurchase' because they are referenced through a protected foreign key: 'BooksIssueData.fk_book_purchase'", <QuerySet [<BooksIssueData: c>]>)


2020-01-09 10:35:55.729348
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 130, in delete_book_purchase
    book_obj.delete()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\base.py", line 936, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 245, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 28, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'BooksPurchase' because they are referenced through a protected foreign key: 'BooksIssueData.fk_book_purchase'", <QuerySet [<BooksIssueData: c>]>)


2020-01-09 10:36:46.314689
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 130, in delete_book_purchase
    book_obj.delete()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\base.py", line 936, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 245, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\deletion.py", line 28, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'BooksPurchase' because they are referenced through a protected foreign key: 'BooksIssueData.fk_book_purchase'", <QuerySet [<BooksIssueData: c>]>)


2020-01-09 17:58:30.448484
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-09 17:58:31.420461
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-09 18:47:53.523117
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'CompanyTypes' not found. 'CompanyTypes' is not a valid view function or pattern name.


2020-01-09 18:48:08.147050
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'CompanyTypes' not found. 'CompanyTypes' is not a valid view function or pattern name.


2020-01-09 18:48:49.599670
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'CompanyTypes' not found. 'CompanyTypes' is not a valid view function or pattern name.


2020-01-09 18:53:25.982098
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Subject' not found. 'Subject' is not a valid view function or pattern name.


2020-01-10 11:01:54.541170
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 280, in profile_user
    address_detail_obj = AddressDetail.objects.get(fk_user_info_id=session)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 417, in get
    self.model._meta.object_name
authentication.models.AddressDetail.DoesNotExist: AddressDetail matching query does not exist.


2020-01-10 11:37:36.786831
Traceback (most recent call last):
  File "E:\tirpude_cms_new\notice\views.py", line 47, in notice
    "semester_obj": semester_obj, "section_obj": section_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Subject' not found. 'Subject' is not a valid view function or pattern name.


2020-01-10 11:37:41.566051
Traceback (most recent call last):
  File "E:\tirpude_cms_new\library\views.py", line 40, in book_purchase
    "book_purchase_obj": book_purchase_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Subject' not found. 'Subject' is not a valid view function or pattern name.


2020-01-10 11:38:27.204896
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Subject' not found. 'Subject' is not a valid view function or pattern name.


2020-01-10 11:43:16.955244
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Subject' not found. 'Subject' is not a valid view function or pattern name.


2020-01-10 11:47:18.267802
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Subject' not found. 'Subject' is not a valid view function or pattern name.


2020-01-10 11:54:47.316186
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Subject' not found. 'Subject' is not a valid view function or pattern name.


2020-01-10 12:11:55.836035
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Subject' not found. 'Subject' is not a valid view function or pattern name.


2020-01-10 13:54:00.520312
Traceback (most recent call last):
  File "E:\tirpude_cms_new\library\views.py", line 40, in book_purchase
    "book_purchase_obj": book_purchase_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course-views' not found. 'course-views' is not a valid view function or pattern name.


2020-01-10 13:54:08.526249
Traceback (most recent call last):
  File "E:\tirpude_cms_new\notice\views.py", line 47, in notice
    "semester_obj": semester_obj, "section_obj": section_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course-views' not found. 'course-views' is not a valid view function or pattern name.


2020-01-10 13:54:09.883072
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course-views' not found. 'course-views' is not a valid view function or pattern name.


2020-01-10 13:54:27.960347
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course-views' not found. 'course-views' is not a valid view function or pattern name.


2020-01-10 13:57:20.724188
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course-views' not found. 'course-views' is not a valid view function or pattern name.


2020-01-10 13:58:39.529290
Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 308, in profile_user
    "address_detail_obj": address_detail_obj, "user_operations_obj": user_operations_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Courses' not found. 'Courses' is not a valid view function or pattern name.


2020-01-13 13:14:16.423177
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'authentication_addressdetail.fk_city_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\authentication\views.py", line 280, in profile_user
    address_detail_obj = AddressDetail.objects.get(fk_user_info_id=session)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 411, in get
    num = len(clone)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1137, in execute_sql
    cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'authentication_addressdetail.fk_city_id' in 'field list'")


2020-01-13 16:39:30.649510
Traceback (most recent call last):
  File "E:\tirpude_cms_new\master_forms\views.py", line 1435, in district
    "district_obj": district_obj, "state_obj": state_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course-views' not found. 'course-views' is not a valid view function or pattern name.


2020-01-13 16:54:53.645364
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'notice_notice.fk_section_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\notice\views.py", line 52, in notice
    "semester_obj": semester_obj, "section_obj": section_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 166, in render
    len_values = len(values)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1137, in execute_sql
    cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'notice_notice.fk_section_id' in 'field list'")


2020-01-13 16:55:04.040659
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'notice_notice.fk_section_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\notice\views.py", line 52, in notice
    "semester_obj": semester_obj, "section_obj": section_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 166, in render
    len_values = len(values)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1137, in execute_sql
    cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'notice_notice.fk_section_id' in 'field list'")


2020-01-13 16:55:33.635825
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'notice_notice.fk_section_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\notice\views.py", line 52, in notice
    "semester_obj": semester_obj, "section_obj": section_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 166, in render
    len_values = len(values)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1137, in execute_sql
    cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'notice_notice.fk_section_id' in 'field list'")


2020-01-13 16:57:22.326257
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'notice_notice.fk_section_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\notice\views.py", line 52, in notice
    "semester_obj": semester_obj, "section_obj": section_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 166, in render
    len_values = len(values)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1137, in execute_sql
    cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'notice_notice.fk_section_id' in 'field list'")


2020-01-13 16:59:52.797877
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'notice_notice.fk_section_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\notice\views.py", line 52, in notice
    "semester_obj": semester_obj, "section_obj": section_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 166, in render
    len_values = len(values)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1137, in execute_sql
    cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'notice_notice.fk_section_id' in 'field list'")


2020-01-13 17:42:57.655379
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list("fk_user_info",
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-13 17:42:58.844733
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list("fk_user_info",
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-13 17:45:57.467548
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'tirpude_cms.notice_notice' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\notice\views.py", line 51, in notice
    "semester_obj": semester_obj, "section_obj": section_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 166, in render
    len_values = len(values)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1137, in execute_sql
    cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'tirpude_cms.notice_notice' doesn't exist")


2020-01-13 17:47:14.938129
Traceback (most recent call last):
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'tirpude_cms.notice_notice' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tirpude_cms_new\notice\views.py", line 51, in notice
    "semester_obj": semester_obj, "section_obj": section_obj})
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\template\defaulttags.py", line 166, in render
    len_values = len(values)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1137, in execute_sql
    cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\tirpude_cms_new\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "E:\tirpude_cms_new\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'tirpude_cms.notice_notice' doesn't exist")


