

2020-01-07 12:03:27.695893
Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\authentication\views.py", line 134, in admin_signup
    obj_sections = Sections.objects.all()
NameError: name 'Sections' is not defined


2020-01-07 12:03:29.951968
Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\authentication\views.py", line 134, in admin_signup
    obj_sections = Sections.objects.all()
NameError: name 'Sections' is not defined


2020-01-08 16:40:15.664005
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:46:10.967181
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:46:15.333440
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:50:44.489176
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:53:39.462467
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:53:42.508723
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:56:17.256095
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:56:19.877243
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 398, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 16:56:41.025466
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'All'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 517, in show_particular_student_book
    book_obj = BooksIssue.objects.filter(fk_user_info_id=student_name)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got 'All'.


2020-01-08 17:00:51.672163
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:00:52.988726
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:01:27.380887
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:01:28.756359
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:15:03.932823
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 80, in filter_author_title
    return HttpResponse(json.dumps(title_list))
UnboundLocalError: local variable 'title_list' referenced before assignment


2020-01-08 17:15:35.484929
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 60, in filter_title
    return HttpResponse(json.dumps(title_list))
UnboundLocalError: local variable 'title_list' referenced before assignment


2020-01-08 17:17:51.111762
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:17:52.396980
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:17:54.708685
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:18:53.446463
Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 80, in filter_author_title
    return HttpResponse(json.dumps(title_list))
UnboundLocalError: local variable 'title_list' referenced before assignment


2020-01-08 17:19:16.636869
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 17:19:18.405437
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 18:01:17.979655
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


2020-01-08 18:01:19.469788
Traceback (most recent call last):
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1768, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tripude_cms\library\views.py", line 396, in issue_filter_student_name
    fk_sections_id=section).values_list('fk_user_info',
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1340, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1371, in _add_q
    check_filterable=check_filterable,
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1301, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\sql\query.py", line 1155, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\tripude_cms\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got ''.


